module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
    jest: true,
  },
  extends: [
    'eslint:recommended',
  ],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  rules: {
    // Only enable basic rules that exist in ESLint core
    'no-unused-vars': 'warn',
    'no-console': 'off',
    'no-debugger': 'warn',
    'no-undef': 'warn',
    'no-unreachable': 'warn',
    'no-constant-condition': 'warn',
    'no-empty': 'warn',
    'no-extra-semi': 'warn',
    'no-irregular-whitespace': 'warn',
    'no-redeclare': 'warn',
    'no-sparse-arrays': 'warn',
    'no-unexpected-multiline': 'warn',
    'use-isnan': 'warn',
    'valid-typeof': 'warn',
    'no-var': 'warn',
    'prefer-const': 'warn',
    'no-duplicate-imports': 'warn',
    'no-useless-rename': 'warn',
    'no-useless-concat': 'warn',
    'no-useless-escape': 'warn',
    'no-useless-return': 'warn',
    'no-else-return': 'warn',
    'no-return-assign': 'warn',
    'no-throw-literal': 'warn',
    'no-undef-init': 'warn',
    'no-undefined': 'warn',
    'no-unneeded-ternary': 'warn',
    'no-unused-expressions': 'warn',
    'no-use-before-define': 'warn',
    'no-useless-call': 'warn',
    'no-useless-computed-key': 'warn',
    'no-useless-constructor': 'warn',
    'no-void': 'warn',
    'no-with': 'warn',
    'radix': 'warn',
    'require-yield': 'warn',
    'use-isnan': 'warn',
    'valid-typeof': 'warn',
    'vars-on-top': 'warn',
    'wrap-iife': 'warn',
    'wrap-regex': 'warn',
    'yoda': 'warn',
  },
  globals: {
    process: 'readonly',
    Buffer: 'readonly',
    __dirname: 'readonly',
    __filename: 'readonly',
    global: 'readonly',
    console: 'readonly',
    module: 'readonly',
    require: 'readonly',
    exports: 'readonly',
  },
};
