[build]
  # Build command for Node.js backend
  command = "npm install && npm run build:netlify"
  # Directory to serve
  publish = "dist"
  # Functions directory for serverless functions
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Completely disable secrets scanning
[build.processing.secrets]
  enabled = false

# Disable all processing that might trigger secrets scanning
[build.processing]
  skip_processing = true

# Redirect all API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
