services:
  - type: web
    name: luxgen-trainer-platform-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_SERVICE_API_KEY
        sync: false
    autoDeploy: true
    branch: main
    repo: susil-bot/luxgen-core
    numInstances: 1
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
