services:
  - type: web
    name: luxgen-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        fromDatabase:
          name: luxgen-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    autoDeploy: true
    branch: main

databases:
  - name: luxgen-mongodb
    plan: free
    databaseName: luxgen