# ========================================
# 📊 PROMETHEUS CONFIGURATION
# ========================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # ========================================
  # 🚀 BACKEND API MONITORING
  # ========================================
  - job_name: 'trainer-platform-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # ========================================
  # 🗄️ MONGODB MONITORING
  # ========================================
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # ========================================
  # 🔴 REDIS MONITORING
  # ========================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # ========================================
  # 🔄 NGINX MONITORING
  # ========================================
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s

  # ========================================
  # 📊 PROMETHEUS SELF-MONITORING
  # ========================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s 